#!/bin/bash

echo "HP scanner monitor for NAS install"

# add the user
username=scanner
group=family
if [[ -z $(grep $username /etc/passwd) ]]; then
	useradd -g family $username
fi

# copy the executable
cp hp-scan-monitor.sh /usr/bin
chmod +x /usr/bin/hp-scan-monitor.sh

# copy the startup control script and enable the service
cp hp-scan-monitor.service /lib/systemd/system
systemctl enable hp-scan-monitor.service
systemctl daemon-reload

# write config file
mkdir -p /etc/hp-scan-monitor
cp scan.xml /etc/hp-scan-monitor

config_file=/etc/hp-scan-monitor/config
if [[ -f $config_file ]]; then
	echo "Using existing file $config_file"
else
	read -p "Enter printer hostname or IP address:" -e printerIP
	read -p "Enter folder for scanned images:" -e output_dir
	echo "#File auto-generated by install script $(date)" > $config_file
	echo "printerIP=$printerIP" >> $config_file
	echo "output_dir=$output_dir" >> $config_file
fi
